version: '3.8'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /persist/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    depends_on:
      - unifi-controller
      - nodered
      - mqtt-broker
      - zwavejs
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C1302060-if01-port0:/dev/ttyUSB1
  zwavejs:
    container_name: zwavejs
    image: zwavejs/zwavejs2mqtt:latest
    volumes:
      - /persist/zwavejs:/usr/src/app/store
    environment:
    - TZ=${TZ}
    restart: unless-stopped
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C1302060-if00-port0:/dev/ttyUSB0
    ports:
      - 8091:8091
      - 3000:3000
  unifi-controller:
    container_name: unifi-controller
    image: linuxserver/unifi-controller:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /persist/unifi-controller:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 500M
    restart: unless-stopped
  letsencrypt:
    container_name: letsencrypt
    image: linuxserver/swag:latest
    restart: unless-stopped
    depends_on:
      - unifi-controller
      - homeassistant
    cap_add:
    - NET_ADMIN
    volumes:
    - /persist/letsencrypt:/config
    - /etc/localtime:/etc/localtime:ro
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - EMAIL=${EMAIL}
    - URL=${DOMAIN}
    - SUBDOMAINS=wildcard
    - VALIDATION=dns
    - DNSPLUGIN=cloudflare
    ports:
    - 80:80
    - 443:443
  nodered:
    container_name: node-red
    restart: unless-stopped
    image: nodered/node-red:latest
    environment:
    - TZ=${TZ}
    volumes:
      - /persist/node-red:/data
    ports:
      - 1880:1880
  mqtt-broker:
    container_name: mqtt-broker
    restart: unless-stopped
    image: eclipse-mosquitto
    volumes:
      - /persist/mosquitto:/mosquitto
    ports:
      - 1883:1883
  octoprint:
    container_name: octoprint
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 81:80
    devices:
     - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyUSB2
     - /dev/v4l/by-id/usb-HD_Web_Camera_HD_Web_Camera_Ucamera001-video-index0:/dev/video0
    volumes:
      - /persist/octoprint:/octoprint
    environment:
     - ENABLE_MJPG_STREAMER=true
    