version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /persist/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyUSB1:/dev/ttyUSB1
  unifi-controller:
    container_name: unifi-controller
    image: linuxserver/unifi-controller:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /persist/unifi-controller:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      WEBPASSWORD=${PIHOLE_WEBPASSWORD}
    # Volumes store your data between container upgrades
    volumes:
      - /persist/pihole/config:/etc/pihole/
      - /persist/pihole/dnsmasq.d/:/etc/dnsmasq.d/
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
